# Generated by Django 6.0.6 on 2026-09-23 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('quotations', '0002_quotation_sent_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=20, verbose_name='動作')),
                ('detail', models.TextField(blank=True, default='', verbose_name='改了什麼')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to=settings.AUTH_USER_MODEL, verbose_name='誰')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='orders.order', verbose_name='訂單')),
                ('quotation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='quotations.quotation', verbose_name='報價單')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('order__isnull', True), ('quotation__isnull', False)), models.Q(('order__isnull', False), ('quotation__isnull', True)), _connector='OR'), name='changelog_one_target')],
            },
        ),
    ]
