# Generated by Django 6.0.6 on 2026-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.CharField(max_length=50, unique=True, verbose_name='型號')),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('price', models.PositiveIntegerField(verbose_name='單價')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='product_price_gt_0')],
            },
        ),
    ]
