# Generated by Django 6.0.6 on 2026-09-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('salesperson', '業務'), ('boss', '老闆')], default='salesperson', max_length=20, verbose_name='角色'),
        ),
    ]
