# Generated by Django 6.0.6 on 2026-09-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quotations', '0002_quotation_sent_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='單號')),
                ('status', models.CharField(choices=[('pending', '待處理'), ('processing', '處理中'), ('done', '完成'), ('void', '已作廢')], default='pending', max_length=12, verbose_name='狀態')),
                ('expected_delivery', models.DateField(blank=True, null=True, verbose_name='預計交付日')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='quotations.quotation', verbose_name='來源報價單')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='數量')),
                ('unit_price', models.PositiveIntegerField(verbose_name='單價')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'void'), _negated=True), fields=('quotation',), name='one_active_order_per_quotation'),
        ),
    ]
