# Generated by Django 6.0.6 on 2026-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('contact', models.CharField(blank=True, default='', max_length=50, verbose_name='聯絡人')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
