# Generated by Django 6.0.6 on 2026-08-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='名稱')),
                ('phone', models.CharField(db_index=True, max_length=30, verbose_name='電話')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
