# Generated by Django 6.0.6 on 2026-08-23 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='單號')),
                ('status', models.CharField(choices=[('draft', '草擬'), ('sent', '已送出'), ('won', '已成交'), ('lost', '沒成')], default='draft', max_length=10, verbose_name='狀態')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='有效期限')),
                ('payment_terms', models.CharField(blank=True, default='完工後三日內付款', max_length=100, verbose_name='付款條件')),
                ('note', models.TextField(blank=True, default='', verbose_name='備註')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer', verbose_name='客戶')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='負責人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='品名')),
                ('qty', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='數量')),
                ('unit_price', models.PositiveIntegerField(verbose_name='單價')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product', verbose_name='來源商品')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gt', 0)), name='item_qty_gt_0')],
            },
        ),
    ]
