# Generated by Django 6.0.6 on 2026-09-23 13:26

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('no', models.CharField(editable=False, max_length=20, unique=True, verbose_name='單號')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='日期')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('sent', '已送出')], default='draft', max_length=10, verbose_name='狀態')),
                ('sent_at', models.DateField(blank=True, null=True, verbose_name='送出日期')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='customers.customer', verbose_name='客戶')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to=settings.AUTH_USER_MODEL, verbose_name='業務')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(verbose_name='數量')),
                ('unit_price', models.PositiveIntegerField(verbose_name='單價')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='products.product', verbose_name='商品')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='報價單')),
            ],
            options={
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('qty__gte', 1)), name='quote_item_qty_gte_1')],
            },
        ),
    ]
