# Generated by Django 6.0.6 on 2026-09-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sent_on',
            field=models.DateField(blank=True, null=True, verbose_name='送出日'),
        ),
    ]
